import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { montserrat } from "./fonts";
import Image from "next/image";
import styles from "./home.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={`${montserrat.className}`} >

        <nav className={styles.navegacion}>
          <a href="" style={{display:"flex"}} ><Image src="/LOGO.jpg" alt="imgLOGO" width={50} height={50} style={{ borderRadius: '50%', marginTop: '-12px', marginRight: '5px' }}/> Comunidad Cristiana Vision de Fe</a>
        </nav>

        {children}</body>
    </html>
  );
}
